import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import { ClerkProvider } from "@clerk/nextjs"
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Job Genie",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Suspense fallback={<div>Loading jobs...</div>}>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
          >
            <Navbar />
            {children}
            <Footer />
            <ToastContainer />
          </body>
        </html>
      </Suspense>
    </ClerkProvider>
  );
}
